# Generated by Django 4.1.4 on 2023-06-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_message_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['is_read', '-created']},
        ),
    ]
