# Generated by Django 4.1.4 on 2023-06-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_review_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-votes_ratio', '-votes_count', '-created']},
        ),
        migrations.AddField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'UP vote'), ('down', 'DOWN vote')], default='up', max_length=5),
            preserve_default=False,
        ),
    ]
